language: node_js
node_js:
- '0.10'
- '0.12'
- iojs
deploy:
  provider: heroku
  api_key:
    secure: CCY6pqS3KAoIl6O6LGZShEjwjX5pOcdX4AGy5/tZkGiHFaJJcpxnq4/32IBUvf8y+EwDEfhLKzVqhGC8a+Sq8KlaDAfoGxLQUfwz5PMm5/SZlBB5Y4Q8X4Nj7kV4WOCSgAWuHzEGh3WEyqA076DRzpx3F9e7I5AyrSZ954thXaukgaQxuWm52+c3c9zv4SYDcsshChm/0khpVpAzFAuTXPK0AvGDXaWXRHQmLItsFKAWWjvfR7DYVE1W7W/y6KBdnzSVyLfUJG1cruEV866V2dP77vwHOBZdI0INSkm5kKtAzfmX4kEEJt5Qj7vsnOAjF9EwuujuWT6n183DVVGoMllbynp2MlXDypjNCVbXxzHsdflPXesWIt1z+HnSYRoJI1syu8NlekR3PF+psB9/LWj4FvKnhIPiFEpSQy99Q5iIu67tljlt5omjMboc0q0ThH0WZCAklrutt+DUiffWpdvIW9OhsUW/ol/XvnSm2J8EsLjfEEBBYFlXrNgYTaMfZO/TKHU5TEHcujnaTiqhh2JnlDKEwT26xuTtrRYl2wbtbKyADGC5wfjNwXOWmVXosbzdZZC6ziEf8Z+5s26cNx/j5PmG3kjmkTFxTIvhKQQ8CsqrPP0zN+P6GyTkir1G9WsqMi26SueRlzr38rP0fnrcP5cVqDtwyS4WJbkILzs=
  app: angular-spa-browserify-example
  on:
    repo: cgmartin/angular-spa-browserify-example
