FROM node:0.12

## Install forever
RUN npm install -g forever gulp

## Set up application folder
RUN mkdir -p /app
WORKDIR /app

## Cache 3rd-party NPM modules
COPY package.json /app/
RUN npm install --unsafe-perm

## Copy source
COPY . /app/

## Build the app
RUN npm run build

## Run static service forever
CMD [ "forever", "-f", "src/server/static-server.js" ]

EXPOSE 8000
