static:
  build: .
  dockerfile: Dockerfile-dev
  command: serve
  volumes:
    - src:/app/src
    - gulpfile.js:/app/gulpfile.js
    - karma.conf.js:/app/karma.conf.js
    - .jscsrc:/app/.jscsrc
    - .jshintrc:/app/.jshintrc
