FROM node:0.12

## Install gulp
RUN npm install -g gulp

## Set up application folder
RUN mkdir -p /app/src
WORKDIR /app

## Cache 3rd-party NPM modules
COPY package.json /app/
RUN npm install --unsafe-perm

## TODO: Cachebust this section to ensure using latest dependencies
#RUN npm install spa-express-static-server@latest

## Expose gulp as default command
ENTRYPOINT ["gulp"]
CMD ["--help"]

EXPOSE 3000 5800
